#!/bin/bash

# Exit on error
set -e

# Build frontend
cd src/main/resources/assets/FrontEndDevelopment
gulp default
cd ../../../../..

# Temporarily disable exit on error
set +e

# Temporarily move node_modules directory
mv src/main/resources/assets/FrontEndDevelopment/node_modules node_modules

# Build jar
mvn clean package

# Move node_modules back
mv node_modules src/main/resources/assets/FrontEndDevelopment/node_modules
